/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated.usuarios'
import { Route as AuthenticatedSedesRouteImport } from './routes/_authenticated.sedes'
import { Route as AuthenticatedSalidasRouteImport } from './routes/_authenticated.salidas'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated.roles'
import { Route as AuthenticatedParqueaderosRouteImport } from './routes/_authenticated.parqueaderos'
import { Route as AuthenticatedOrdenesCompraRouteImport } from './routes/_authenticated.ordenes-compra'
import { Route as AuthenticatedMovimientosRouteImport } from './routes/_authenticated.movimientos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated.categorias'
import { Route as AuthenticatedCanalesRouteImport } from './routes/_authenticated.canales'
import { Route as AuthenticatedAsignacionesRouteImport } from './routes/_authenticated.asignaciones'
import { Route as AuthenticatedActivosRouteImport } from './routes/_authenticated.activos'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSedesRoute = AuthenticatedSedesRouteImport.update({
  id: '/sedes',
  path: '/sedes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalidasRoute = AuthenticatedSalidasRouteImport.update({
  id: '/salidas',
  path: '/salidas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParqueaderosRoute =
  AuthenticatedParqueaderosRouteImport.update({
    id: '/parqueaderos',
    path: '/parqueaderos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdenesCompraRoute =
  AuthenticatedOrdenesCompraRouteImport.update({
    id: '/ordenes-compra',
    path: '/ordenes-compra',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMovimientosRoute =
  AuthenticatedMovimientosRouteImport.update({
    id: '/movimientos',
    path: '/movimientos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCanalesRoute = AuthenticatedCanalesRouteImport.update({
  id: '/canales',
  path: '/canales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAsignacionesRoute =
  AuthenticatedAsignacionesRouteImport.update({
    id: '/asignaciones',
    path: '/asignaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActivosRoute = AuthenticatedActivosRouteImport.update({
  id: '/activos',
  path: '/activos',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activos': typeof AuthenticatedActivosRoute
  '/asignaciones': typeof AuthenticatedAsignacionesRoute
  '/canales': typeof AuthenticatedCanalesRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/ordenes-compra': typeof AuthenticatedOrdenesCompraRoute
  '/parqueaderos': typeof AuthenticatedParqueaderosRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/salidas': typeof AuthenticatedSalidasRoute
  '/sedes': typeof AuthenticatedSedesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activos': typeof AuthenticatedActivosRoute
  '/asignaciones': typeof AuthenticatedAsignacionesRoute
  '/canales': typeof AuthenticatedCanalesRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/movimientos': typeof AuthenticatedMovimientosRoute
  '/ordenes-compra': typeof AuthenticatedOrdenesCompraRoute
  '/parqueaderos': typeof AuthenticatedParqueaderosRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/salidas': typeof AuthenticatedSalidasRoute
  '/sedes': typeof AuthenticatedSedesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activos': typeof AuthenticatedActivosRoute
  '/_authenticated/asignaciones': typeof AuthenticatedAsignacionesRoute
  '/_authenticated/canales': typeof AuthenticatedCanalesRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/movimientos': typeof AuthenticatedMovimientosRoute
  '/_authenticated/ordenes-compra': typeof AuthenticatedOrdenesCompraRoute
  '/_authenticated/parqueaderos': typeof AuthenticatedParqueaderosRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/salidas': typeof AuthenticatedSalidasRoute
  '/_authenticated/sedes': typeof AuthenticatedSedesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/activos'
    | '/asignaciones'
    | '/canales'
    | '/categorias'
    | '/dashboard'
    | '/movimientos'
    | '/ordenes-compra'
    | '/parqueaderos'
    | '/roles'
    | '/salidas'
    | '/sedes'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/activos'
    | '/asignaciones'
    | '/canales'
    | '/categorias'
    | '/dashboard'
    | '/movimientos'
    | '/ordenes-compra'
    | '/parqueaderos'
    | '/roles'
    | '/salidas'
    | '/sedes'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/activos'
    | '/_authenticated/asignaciones'
    | '/_authenticated/canales'
    | '/_authenticated/categorias'
    | '/_authenticated/dashboard'
    | '/_authenticated/movimientos'
    | '/_authenticated/ordenes-compra'
    | '/_authenticated/parqueaderos'
    | '/_authenticated/roles'
    | '/_authenticated/salidas'
    | '/_authenticated/sedes'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sedes': {
      id: '/_authenticated/sedes'
      path: '/sedes'
      fullPath: '/sedes'
      preLoaderRoute: typeof AuthenticatedSedesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salidas': {
      id: '/_authenticated/salidas'
      path: '/salidas'
      fullPath: '/salidas'
      preLoaderRoute: typeof AuthenticatedSalidasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parqueaderos': {
      id: '/_authenticated/parqueaderos'
      path: '/parqueaderos'
      fullPath: '/parqueaderos'
      preLoaderRoute: typeof AuthenticatedParqueaderosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ordenes-compra': {
      id: '/_authenticated/ordenes-compra'
      path: '/ordenes-compra'
      fullPath: '/ordenes-compra'
      preLoaderRoute: typeof AuthenticatedOrdenesCompraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movimientos': {
      id: '/_authenticated/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof AuthenticatedMovimientosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/canales': {
      id: '/_authenticated/canales'
      path: '/canales'
      fullPath: '/canales'
      preLoaderRoute: typeof AuthenticatedCanalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asignaciones': {
      id: '/_authenticated/asignaciones'
      path: '/asignaciones'
      fullPath: '/asignaciones'
      preLoaderRoute: typeof AuthenticatedAsignacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activos': {
      id: '/_authenticated/activos'
      path: '/activos'
      fullPath: '/activos'
      preLoaderRoute: typeof AuthenticatedActivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivosRoute: typeof AuthenticatedActivosRoute
  AuthenticatedAsignacionesRoute: typeof AuthenticatedAsignacionesRoute
  AuthenticatedCanalesRoute: typeof AuthenticatedCanalesRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMovimientosRoute: typeof AuthenticatedMovimientosRoute
  AuthenticatedOrdenesCompraRoute: typeof AuthenticatedOrdenesCompraRoute
  AuthenticatedParqueaderosRoute: typeof AuthenticatedParqueaderosRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSalidasRoute: typeof AuthenticatedSalidasRoute
  AuthenticatedSedesRoute: typeof AuthenticatedSedesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivosRoute: AuthenticatedActivosRoute,
  AuthenticatedAsignacionesRoute: AuthenticatedAsignacionesRoute,
  AuthenticatedCanalesRoute: AuthenticatedCanalesRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMovimientosRoute: AuthenticatedMovimientosRoute,
  AuthenticatedOrdenesCompraRoute: AuthenticatedOrdenesCompraRoute,
  AuthenticatedParqueaderosRoute: AuthenticatedParqueaderosRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSalidasRoute: AuthenticatedSalidasRoute,
  AuthenticatedSedesRoute: AuthenticatedSedesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
